### ISSUE TITLE
Support branch auto-delete after PR merge

### ISSUE THREAD

**Issue by antonakospanos** [Workable/oneflow#52]
![Screenshot 2019-10-14 at 11 47 42 AM](https://user-images.githubusercontent.com/42936184/66740037-c892de80-ee7a-11e9-88f1-f473e15b1720.png)

We would like to enable Github's branch auto-delete after merging of the corresponding pull request. 

Can we support this flow in *oneflow* too? The merged branch could have either been already deleted by Github or else shall be deleted by oneflow.

**Comment by nikostoulas** [comment]
I think this is the place that should handle errors: https://github.com/Workable/oneflow/blob/master/src/lib/helpers.ts#L107
@antonakospanos care to do it?

**Comment by antonakospanos** [comment]
Ok, I can test it during the next days

**Comment by antonakospanos** [comment]
https://github.com/Workable/oneflow/pull/55
